### ISSUE TITLE
image file blocked.png is missing

### ISSUE THREAD

**Issue by wushuzh** [OliveTin/docs.olivetin.app#21]
When I read [section Concurrency](https://docs.olivetin.app/concurrency.html) of the doc, I found the image file `images/blocked.png` is missing.

![1721270999447](https://github.com/user-attachments/assets/a3f6801f-3add-4b5e-816a-a04a26315783)

Please help to confirm.

**Comment by jamesread** [comment]
Thanks for reporting, I genuinely don't know where that image went! Took a new screenshot and uploaded it; 

![image](https://github.com/user-attachments/assets/7260a2fb-2333-40a6-9324-ede519e0322d)
