### ISSUE TITLE
Documentation Search Functionality

### ISSUE THREAD

**Issue by Josh-su** [OliveTin/docs.olivetin.app#28]
I'm often lost in the documentation. A search function would be incredibly helpful for quickly finding information

**Comment by jamesread** [comment]
@Josh-su Check out http://prettydocs.olivetin.app ?

**Comment by Josh-su** [comment]
Thanks ! The search function on http://prettydocs.olivetin.app/ works fine. I did notice that there are no photos and some search results return multiple times, but I'm just glad to have the ability to search. It really helps since I always forget which category contains the explanation I need.

Appreciate your help!

**Comment by jamesread** [comment]
That's good - yeah I'm aware it doesn't yet do images, it's one of the several things I need to fix before it goes live
