### ISSUE TITLE
Documentation wrong (hideNavigation: true)

### ISSUE THREAD

**Issue by TheRaven500** [OliveTin/docs.olivetin.app#6]
Hi
On the Docupage:
https://docs.olivetin.app/toggle-webui.html

"hideNavigation: true" is wrong i think, OliveTin does not start with this parameter.
Maybe it has changed some time ago?
Should be "showNavigation: false" indeed.

MerryXmas and Greetings

**Comment by jamesread** [comment]
@TheRaven500 that should be fixed now, would you mind sanity checking me and check that it reads OK for you too?

**Comment by TheRaven500** [comment]
@jamesread thank you very much for fixing this so fast! Looks good. The only thing i ask me: Does it need quots " like logLevel: "INFO"? I mean only for cosmetic reason. If it has quots it looks more similar to "INFO".

**Comment by jamesread** [comment]
Hey @TheRaven500 , good question, but actually it won't work properly with quotes. logLevel needs a string argument (text), and needs quotes for that. Whereas showNavigation needs a boolean argument (true/false). It might work, but it's cleaner this way :-) 

Merry Christmas!

**Comment by TheRaven500** [comment]
Ok, then it is ok like it is. :-)
Merry Christmas back to you.
